# Type Labels
- name: bug
  color: "ff0000"
  description: Bug or error in the code
- name: enhancement
  color: "00ff00"
  description: New feature or improvement
- name: documentation
  color: "0000ff"
  description: Documentation updates or fixes
- name: question
  color: "800080"
  description: Question or clarification needed

# Status Labels
- name: in progress
  color: "ffff00"
  description: Work in progress
- name: review needed
  color: "ff8800"
  description: PR requires review
- name: ready to merge
  color: "88ff88"
  description: PR reviewed and ready to merge
- name: wontfix
  color: "000000"
  description: Issue will not be fixed

# Priority Labels (optional)
- name: high priority
  color: "880000"
  description: Needs urgent attention
- name: low priority
  color: "885500"
  description: Can be addressed later