# Typ-Labels
- name: bug
  color: "ff0000"
  description: Fehler im Code
- name: enhancement
  color: "00ff00"
  description: Neue Funktionalität/Vorschläge
- name: documentation
  color: "0000ff"
  description: Änderungen an der Dokumentation
- name: question
  color: "800080"
  description: Fragen oder Unklarheiten

# Status-Labels
- name: in progress
  color: "ffff00"
  description: Wird gerade bearbeitet
- name: review needed
  color: "ff8800"
  description: Wartet auf Review
- name: ready to merge
  color: "88ff88"
  description: PR geprüft, bereit zum Merge
- name: wontfix
  color: "000000"
  description: Wird nicht umgesetzt

# Priorität (optional)
- name: high priority
  color: "880000"
  description: Muss bald gelöst werden
- name: low priority
  color: "885500"
  description: Kann warten