"""initial tables

Revision ID: 36b2908baacc
Revises: 5c09a6dc2bfa
Create Date: 2026-02-16 18:47:09.323406

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36b2908baacc'
down_revision: Union[str, Sequence[str], None] = '5c09a6dc2bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'email')
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
