"""initial tables

Revision ID: 8f5fb9970fb5
Revises: a4ebdf5a2971
Create Date: 2026-02-16 18:56:15.967828

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f5fb9970fb5'
down_revision: Union[str, Sequence[str], None] = 'a4ebdf5a2971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
